"""empty message

Revision ID: 7d437513dbcc
Revises: ae2d98c1db6a
Create Date: 2019-12-04 21:13:49.707216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d437513dbcc'
down_revision = 'ae2d98c1db6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('profile_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
