"""empty message

Revision ID: 99adbd67b4e3
Revises: d67f8c46e34e
Create Date: 2019-12-04 20:43:40.093837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99adbd67b4e3'
down_revision = 'd67f8c46e34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
