"""empty message

Revision ID: ae2d98c1db6a
Revises: 99adbd67b4e3
Create Date: 2019-12-04 20:53:48.908342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2d98c1db6a'
down_revision = '99adbd67b4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET profile_image = 'default_profile_img'")
    # op.alter_column('users', 'profile_image',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
