"""empty message

Revision ID: d67f8c46e34e
Revises: e12b78b48315
Create Date: 2019-12-04 20:37:26.876328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67f8c46e34e'
down_revision = 'e12b78b48315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('profile_image', sa.String(), nullable=False))
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('profile_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
