"""empty message

Revision ID: dfb7ebb922b9
Revises: 70973c0cef8f
Create Date: 2019-12-04 21:38:07.855510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb7ebb922b9'
down_revision = '70973c0cef8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=False, server_default='default_profile_img'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
