"""empty message

Revision ID: faac68ededb2
Revises: dfb7ebb922b9
Create Date: 2019-12-04 22:34:34.380507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faac68ededb2'
down_revision = 'dfb7ebb922b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('profile_image')
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=False, server_default='default_profile_img.png'))
    # op.alter_column('users', 'profile_image',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False,
    #            existing_server_default=sa.text("'default_profile_img.png'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'default_profile_img'"))
    # ### end Alembic commands ###
