"""empty message

Revision ID: e0c6f213bdce
Revises: 9b9614f748e7
Create Date: 2019-11-27 15:37:00.963681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c6f213bdce'
down_revision = '9b9614f748e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies') as batch_op:
        batch_op.drop_column('breed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
